// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL_DataAccesLayer.Context;

namespace _1_DAL_DataAccesLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211108090228_cv12")]
    partial class cv12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ChatLieu", b =>
                {
                    b.Property<string>("MaChatLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("TenChatLieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChatLieu")
                        .HasName("PK__ChatLieu__453995BC8D0BF58A");

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D4639533FC716D6C");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.DonViTinh", b =>
                {
                    b.Property<string>("MaDonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDonViTinh")
                        .HasName("PK__DonViTin__ADD89AA2022E2F1B");

                    b.HasIndex("MaChatLieu");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayXuat")
                        .HasColumnType("date");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13BF13FB2F1");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.HoaDonChiTiet", b =>
                {
                    b.Property<string>("MaHoaDonChiTiet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThongTin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDonChiTiet")
                        .HasName("PK__HoaDonCh__6C2FD0CE34F8C7B8");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaThongTin");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.LoaiHang", b =>
                {
                    b.Property<string>("MaLoaiHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("TenLoaiHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaLoaiHang")
                        .HasName("PK__LoaiHang__5EEA4160BAF12530");

                    b.ToTable("LoaiHang");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNhaCungCap")
                        .HasName("PK__NhaCungC__53DA9205C78767AF");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int");

                    b.Property<string>("SoCmnd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SoCMND");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA474BA15FD3");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__1470EF3B7D606C9C");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.PhieuNhapChiTiet", b =>
                {
                    b.Property<string>("MaCtphieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCTPhieuNhap");

                    b.Property<double?>("DonGiaNhap")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThongTin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaCtphieuNhap")
                        .HasName("PK__PhieuNha__7920817423F704B8");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaThongTin");

                    b.ToTable("PhieuNhapChiTiet");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442DF37C2630");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ThongTinSanPham", b =>
                {
                    b.Property<string>("MaThongTin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MaDonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLoaiHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaXuatXu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<double?>("TrongLuong")
                        .HasColumnType("float");

                    b.HasKey("MaThongTin")
                        .HasName("PK__ThongTin__5E4CADDCEDD1F21C");

                    b.HasIndex("MaDonViTinh");

                    b.HasIndex("MaLoaiHang");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaXuatXu");

                    b.ToTable("ThongTinSanPham");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.XuatXu", b =>
                {
                    b.Property<string>("MaXuatXu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("TenNuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaXuatXu")
                        .HasName("PK__XuatXu__27BB6B197CC59C96");

                    b.ToTable("XuatXu");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.DonViTinh", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.ChatLieu", "MaChatLieuNavigation")
                        .WithMany("DonViTinhs")
                        .HasForeignKey("MaChatLieu")
                        .HasConstraintName("FK__DonViTinh__MaCha__1A14E395")
                        .IsRequired();

                    b.Navigation("MaChatLieuNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.HoaDon", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__HoaDon__MaNhanVi__15502E78")
                        .IsRequired();

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__HoaDonChi__MaHoa__2E1BDC42")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccesLayer.Models.ThongTinSanPham", "MaThongTinNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaThongTin")
                        .HasConstraintName("FK__HoaDonChi__MaTho__2F10007B");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaThongTinNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.NhanVien", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NhanVien__MaChuc__1273C1CD")
                        .IsRequired();

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.PhieuNhap", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .HasConstraintName("FK__PhieuNhap__MaNha__24927208")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccesLayer.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__PhieuNhap__MaNha__25869641")
                        .IsRequired();

                    b.Navigation("MaNhaCungCapNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.PhieuNhapChiTiet", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.PhieuNhap", "MaPhieuNhapNavigation")
                        .WithMany("PhieuNhapChiTiets")
                        .HasForeignKey("MaPhieuNhap")
                        .HasConstraintName("FK__PhieuNhap__MaPhi__31EC6D26")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccesLayer.Models.ThongTinSanPham", "MaThongTinNavigation")
                        .WithMany("PhieuNhapChiTiets")
                        .HasForeignKey("MaThongTin")
                        .HasConstraintName("FK__PhieuNhap__MaTho__32E0915F")
                        .IsRequired();

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaThongTinNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ThongTinSanPham", b =>
                {
                    b.HasOne("_1_DAL_DataAccesLayer.Models.DonViTinh", "MaDonViTinhNavigation")
                        .WithMany("ThongTinSanPhams")
                        .HasForeignKey("MaDonViTinh")
                        .HasConstraintName("FK__ThongTinS__MaDon__286302EC")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccesLayer.Models.LoaiHang", "MaLoaiHangNavigation")
                        .WithMany("ThongTinSanPhams")
                        .HasForeignKey("MaLoaiHang")
                        .HasConstraintName("FK__ThongTinS__MaLoa__29572725")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccesLayer.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ThongTinSanPhams")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__ThongTinS__MaSan__2B3F6F97")
                        .IsRequired();

                    b.HasOne("_1_DAL_DataAccesLayer.Models.XuatXu", "MaXuatXuNavigation")
                        .WithMany("ThongTinSanPhams")
                        .HasForeignKey("MaXuatXu")
                        .HasConstraintName("FK__ThongTinS__MaXua__2A4B4B5E")
                        .IsRequired();

                    b.Navigation("MaDonViTinhNavigation");

                    b.Navigation("MaLoaiHangNavigation");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaXuatXuNavigation");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ChatLieu", b =>
                {
                    b.Navigation("DonViTinhs");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.DonViTinh", b =>
                {
                    b.Navigation("ThongTinSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.LoaiHang", b =>
                {
                    b.Navigation("ThongTinSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.PhieuNhap", b =>
                {
                    b.Navigation("PhieuNhapChiTiets");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.SanPham", b =>
                {
                    b.Navigation("ThongTinSanPhams");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.ThongTinSanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("PhieuNhapChiTiets");
                });

            modelBuilder.Entity("_1_DAL_DataAccesLayer.Models.XuatXu", b =>
                {
                    b.Navigation("ThongTinSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
